# Generated by Django 4.0.3 on 2022-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
