# Generated by Django 4.0.3 on 2022-03-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0002_remove_shoppinglist_url_shoppinglist_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='profile_img',
            new_name='product_img',
        ),
    ]
