# Generated by Django 4.0.3 on 2022-04-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0002_user_address_user_nationality_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
