# Generated by Django 4.0.3 on 2022-04-22 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0003_rename_profile_img_shoppinglist_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='added_to_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
