# Generated by Django 4.0.3 on 2022-05-08 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0005_user_postal_code_user_street_no_checkoutorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutorder',
            options={'ordering': ['expected_delivery']},
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='expected_delivery',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='ordered_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsCommentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsListings', to='quanta.shoppinglist'),
        ),
    ]
