# Generated by Django 4.0.3 on 2022-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0006_alter_checkoutorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='products',
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='product_ordered',
            field=models.ManyToManyField(blank=True, related_name='productsCheckoutOrder', to='quanta.shoppinglist'),
        ),
    ]
