# Generated by Django 4.0.3 on 2022-05-09 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0008_alter_checkoutorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quanta.shoppinglist'),
        ),
    ]
